<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class news extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert([
            ['id'=>1,'name'=>'Mách Bạn Chọn Hoa Chúc Mừng Khai Trương Cửa Hàng','news_alias'=>'mach-ban-chon-hoa-chuc-mung-khai-truong-cua-hang','content'=>'Quà tặng là một phần không thể thiếu trong đời sống kinh doanh của mọi người. Tặng quà cho khách hàng là một lời cảm ơn tới khách hàng. Cũng có thể tăng cường mối quan hệ giữa khách hàng và công ty. Trong các dịp như khai trương, mở chi nhánh, hay kỷ niệm thành lập…. thì chúng ta nên gửi lẵng hoa chúc mừng đẹp và đầy sang trọng.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống. Những sắc màu của niềm vui thật phù hợp với ngày lễ khai trương.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/05/chuc-mung-khai-truong-cua-hang.jpg','status'=>1],
            ['id'=>2,'name'=>'Những Mẫu Bó Hoa Loa Kèn Đẹp Tặng Sinh Nhật','news_alias'=>'nhung-mau-bo-hoa-loa-ken-dep-tang-sinh-nhat','content'=>'Cứ mỗi dịp tháng Tư về, bạn lại bắt gặp những gánh hàng hoa loa kèn thân thương trên phố phường Hà Nội.  Những gánh hàng hoa loa kèn đã trở nên thân thuộc với những người con Hà Nội. Hoa loa kèn thân thuộc đến nỗi người ta coi đó là một dấu hiệu mỗi khi hè về.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2019/07/bo-hoa-loa-ken-trang-e1648458472228.jpg','status'=>1],
            ['id'=>3,'name'=>'Những lưu ý khi chọn hoa mừng khai trương công ty','news_alias'=>'nhung-luu-y-khi-chon-hoa-mung-khai-truong-cong-ty','content'=>'Hoa mừng khai trương công ty là một hạng mục quan trọng. Bởi đó không chỉ là món quà dành tặng nhau. Mà đôi khi còn là đại diện cho công ty bạn khi đi dự lễ khai trương, kỷ niệm.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/04/hoa-mung-khai-truong.jpg','status'=>1],
            ['id'=>4,'name'=>'Những Mẫu Bó Hoa Cúc Họa Mi Đẹp Nhất Tại Hanoi Florist','news_alias'=>'nhung-mau-bo-hoa-cuc-hoa-mi-dep-nhat-tai-hanoi-florist','content'=>'Hoa mừng khai trương công ty là một hạng mục quan trọng. Bởi đó không chỉ là món quà dành tặng nhau. Mà đôi khi còn là đại diện cho công ty bạn khi đi dự lễ khai trương, kỷ niệm.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2020/11/bo-hoa-cuc-hoa-mi-dep-nhat-e1630750505901.jpg','status'=>1],
            ['id'=>5,'name'=>'Tháng Tư gọi hoa loa kèn về trên phố…','news_alias'=>'thang-tu-hoa-loa-ken-ve-tren-pho','content'=>'Khi tiết trời Hà Nội ấm dần lên, lấp lánh những vạt nắng tháng tư cũng là lúc loa kèn cùng những gánh hàng hoa khoe sắc trên nhiều con phố…Hoa loa kèn trắng đã trở nên rất đỗi thân thương với những người con Hà Nội. Mời bạn cùng ngắm những hình ảnh đẹp về hoa loa kèn trên phố phường Hà Nội.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống. Những sắc màu của niềm vui thật phù hợp với ngày lễ khai trương.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/03/8-hoa-loa-ken-ha-noi-mytour-5-e1648527379253.jpg','status'=>1],
            ['id'=>6,'name'=>'Những Mẫu Bó Hoa Loa Kèn Đẹp','news_alias'=>'nhung-mau-bo-hoa-loa-ken-dep','content'=>'Cứ mỗi dịp tháng Tư về, bạn lại bắt gặp những gánh hàng hoa loa kèn thân thương trên phố phường Hà Nội.  Những gánh hàng hoa loa kèn đã trở nên thân thuộc với những người con Hà Nội. Hoa loa kèn thân thuộc đến nỗi người ta coi đó là một dấu hiệu mỗi khi hè về.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2019/07/bo-hoa-loa-ken-trang-e1648458472228.jpg','status'=>1],
            ['id'=>7,'name'=>'Hoa Hướng Dương Sinh Nhật Đẹp Rạng Rỡ','news_alias'=>'hoa-huong-duong-sinh-nhat-dep-rang-ro','content'=>'Hoa mừng khai trương công ty là một hạng mục quan trọng. Bởi đó không chỉ là món quà dành tặng nhau. Mà đôi khi còn là đại diện cho công ty bạn khi đi dự lễ khai trương, kỷ niệm.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2021/03/lang-huong-duong-sinh-nhat-dep-e1616340605664.jpg','status'=>1],
            ['id'=>8,'name'=>'Bó Hoa Cúc Họa Mi Đẹp Nhất Tại Hanoi Florist','news_alias'=>'bo-hoa-cuc-hoa-mi-dep-nhat-tai-hanoi-florist','content'=>'Hoa mừng khai trương công ty là một hạng mục quan trọng. Bởi đó không chỉ là món quà dành tặng nhau. Mà đôi khi còn là đại diện cho công ty bạn khi đi dự lễ khai trương, kỷ niệm.','description'=>'Những màu sắc nổi bật như sắc đỏ, vàng thường được chọn nhiều nhất. Hai gam màu nổi bật này thường tạo ấn tượng mạnh mẽ với mọi người. Cũng điều đó giúp cho không gian buổi lễ khai trương thêm phần vui tươi đầy sức sống.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/02/hoa-cuc-mau-don-hong-dep-300x300.jpg','status'=>1],
        ]);    
    }
}
