<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product')->insert([
            ['id'=>1,'name'=>'Bó Hoa Sinh Nhật Đẹp Tặng Bạn','product_alias'=>'bo-hoa-sinh-nhat-dep-tang-ban','cat_id'=>1,'price'=>300000,'old_price'=>450000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/10/mau-hoa-tang-sinh-nhat-300x300.jpg','status'=>1],
            ['id'=>2,'name'=>'Bó Hoa Hồng Nhung Đỏ','product_alias'=>'bo-hoa-hong-nhung-do','cat_id'=>1,'price'=>400000,'old_price'=>500000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/08/hoa-hong-nhung-do-2-e1661144721860-300x300.png','status'=>1],
            ['id'=>3,'name'=>'Bó Hoa Sen Trắng Đẹp Tặng Sinh Nhật','product_alias'=>'bo-hoa-sen-trang-dep-tang-sinh-nhat','cat_id'=>1,'price'=>250000,'old_price'=>300000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/07/bo-hoa-sen-trang-300x300.jpg','status'=>1],
            ['id'=>4,'name'=>'Bó Hoa Sen Trắng Xanh','product_alias'=>'bo-hoa-sen-trang-xanh','cat_id'=>1,'price'=>300000,'old_price'=>450000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/07/bo-hoa-sen-trang-300x300.jpg','status'=>1],
            ['id'=>5,'name'=>'Bó Hoa Hồng Đỏ Tặng Người Yêu','product_alias'=>'bo-hoa-hong-do-tang-nguoi-yeu','cat_id'=>1,'price'=>500000,'old_price'=>600000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/04/hoa-hong-tang-nguoi-yeu-300x300-1.jpg','status'=>1],
            ['id'=>6,'name'=>'Bó Hoa Sinh Nhật Ý Nghĩa','product_alias'=>'bo-hoa-sinh-nhat-y-nghia','cat_id'=>1,'price'=>300000,'old_price'=>450000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/03/hoa-sinh-nhat-ha-noi.jpg','status'=>1],
            ['id'=>7,'name'=>'Hoa Cúc Mẫu Đơn Hà Lan Xanh Dương','product_alias'=>'hoa-cuc-mau-don-ha-lan-xanh-duong','cat_id'=>1,'price'=>600000,'old_price'=>800000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/hoa-cuc-mau-don-xanh-768x768.jpg','status'=>1],
            ['id'=>8,'name'=>'Hoa Sinh Nhật Dễ Thương','product_alias'=>'hoa-sinh-nhat-de-thuong','cat_id'=>1,'price'=>400000,'old_price'=>600000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/bo-hoa-dep-1-768x1024.jpg','status'=>1],
            ['id'=>9,'name'=>'Giỏ Hoa Đẹp Tặng Khai Trương','product_alias'=>'gio-hoa-dep-tang-khai-truong','cat_id'=>2,'price'=>300000,'old_price'=>500000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2020/10/mau-hoa-dep-tang-ngay-20-10-scaled-e1602531663543-300x300.jpg','status'=>1],
            ['id'=>10,'name'=>'Giỏ Hoa Sinh Nhật Đẹp','product_alias'=>'gio-hoa-sinh-nhat-dep','cat_id'=>2,'price'=>400000,'old_price'=>500000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/09/gio-hoa-sinh-nhat.jpg','status'=>1],
            ['id'=>11,'name'=>'Giỏ Hoa Cúc Mẫu Đơn','product_alias'=>'gio-hoa-cuc-mau-don','cat_id'=>2,'price'=>500000,'old_price'=>600000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/gio-cuc-mau-don-hong-scaled-e1645418768823.jpg','status'=>1],
            ['id'=>12,'name'=>'Giỏ Hoa Sinh Nhật Đẹp','product_alias'=>'gio-hoa-sinh-nhat-dep','cat_id'=>2,'price'=>600000,'old_price'=>800000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/gio-hoa-cuc-mau-don-scaled-e1645432694428.jpeg','status'=>1],
            ['id'=>13,'name'=>'Giỏ Hoa Hướng Dương','product_alias'=>'gio-hoa-huong-duong','cat_id'=>2,'price'=>400000,'old_price'=>500000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/gio-hoa-cuc-mau-don-scaled-e1645432694428.jpeg','status'=>1],
            ['id'=>14,'name'=>'Giỏ Hoa Tặng Nam Đẹp ','product_alias'=>'gio-hoa-tang-nam-dep','cat_id'=>2,'price'=>700000,'old_price'=>900000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2020/11/gio-hoa-tone-trang-xanh-e1606724238591-300x300.jpg','status'=>1],
            ['id'=>15,'name'=>'Giỏ Hoa Hướng Dương Tặng Sinh Nhật Ý Nghĩa','product_alias'=>'gio-hoa-huong-duong-tang-sinh-nhat-y-nghia','cat_id'=>2,'price'=>300000,'old_price'=>400000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/06/bo-huong-duong-tang-sinh-nhat-e1622627555529-300x300.jpg','status'=>1],
            ['id'=>16,'name'=>'Giỏ Hoa Cúc Mẫu Đơn Đỏ','product_alias'=>'gio-hoa-cuc-mau-don-do','cat_id'=>2,'price'=>800000,'old_price'=>1000000,'content'=>'Bên cạnh những mẫu bó hoa hồng quen thuộc thì hoa cẩm tú cầu với tone màu trắng xanh lại mang đến cảm giác mới lạ cho người được nhận','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist. Mọi người thường hay chọn hoa hồng đỏ làm món quà tặng nhân dịp sinh nhật người mình thương. Và nên chọn bó hoa nào để vừa xinh xắn và cũng vừa ý nghĩa?','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/02/gio-cuc-mau-don-do-300x300.jpeg','status'=>1],
            ['id'=>17,'name'=>'Vòng Hoa Tang Lễ Đẹp','product_alias'=>'vong-hoa-tang-le-dep','cat_id'=>3,'price'=>1000000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/11/vong-hoa-tang-le-dep.png','status'=>1],
            ['id'=>18,'name'=>'Đặt Vòng Hoa Tang Lễ Tại Hà Nội','product_alias'=>'dat-vong-hoa-tang-le-tai-ha-noi','cat_id'=>3,'price'=>1200000,'old_price'=>1500000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/11/vong-hoa-tang-le-tai-ha-noi.jpg','status'=>1],
            ['id'=>19,'name'=>'Đặt Vòng Hoa Đám Tang Tại Hà Nội','product_alias'=>'dat-vong-hoa-dam-tang-tai-ha-noi','cat_id'=>3,'price'=>1000000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/11/dat-vong-hoa-dam-tang.png','status'=>1],
            ['id'=>20,'name'=>'Vòng Hoa Đám Tang Đẹp','product_alias'=>'vong-hoa-dam-tang-dep','cat_id'=>3,'price'=>1000000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/11/vong-hoa-dam-tang.jpg','status'=>1],
            ['id'=>21,'name'=>'Vòng Hoa Viếng Đám Tang','product_alias'=>'vong-hoa-vieng-dam-tang','cat_id'=>3,'price'=>900000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/07/gui-hoa-vieng-tai-ha-noi-e1626705041449-300x300.jpg','status'=>1],
            ['id'=>22,'name'=>'Vòng Hoa Tang Lễ Đẹp Tại Hà Nội','product_alias'=>'dat-vong-hoa-tang-le-dep-tai-ha-noi','cat_id'=>3,'price'=>1500000,'old_price'=>2000000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/07/vong-hoa-chia-buon-e1627137091175-300x300.jpg','status'=>1],
            ['id'=>23,'name'=>'Đặt Vòng Hoa Đám Tang Tại Hà Nội Mới','product_alias'=>'dat-vong-hoa-dam-tang-tai-ha-noi-moi','cat_id'=>3,'price'=>1000000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/07/hoa-vieng-tai-ha-noi-300x300.jpg','status'=>1],
            ['id'=>24,'name'=>'Vòng Hoa Đám Tang Đẹp Nhất','product_alias'=>'vong-hoa-dam-tang-dep-nhat','cat_id'=>3,'price'=>1000000,'old_price'=>1200000,'content'=>'Vòng hoa tang lễ đẹp rẻ luôn sẵn sàng tại Hanoi Florist. Bên cạnh sắc vàng của hoa lan trang trọng, kệ hoa viếng được tạo điểm nhấn bằng những bông hướng dương nhí.','description'=>'Những sắc hoa thay lời thành kính  phân ưu với gia đình thân quyến.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/07/hoa-vieng-dam-tang-300x300.jpg','status'=>1],
            ['id'=>25,'name'=>'Hộp Hoa Hồng Sáp Đẹp','product_alias'=>'hop-hoa-hong-sap-dep','cat_id'=>4,'price'=>800000,'old_price'=>1000000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/03/hop-hoa-hong-dep-768x905.jpg','status'=>1],
            ['id'=>26,'name'=>'Bó Hoa Hồng Sáp','product_alias'=>'bo-hoa-hong-sap','cat_id'=>4,'price'=>700000,'old_price'=>900000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/03/bo-hoa-hong-sap-do-e1647847645466-768x837.jpg','status'=>1],
            ['id'=>27,'name'=>'Bó Hoa Sen Sáp Hồng Đẹp','product_alias'=>'bo-hoa-sen-sap-hong-dep','cat_id'=>4,'price'=>900000,'old_price'=>1000000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/07/bo-hoa-sen-hong.jpg','status'=>1],
            ['id'=>28,'name'=>'Bó Hoa Hồng Sáp Đẹp','product_alias'=>'bo-hoa-hong-sap-dep','cat_id'=>4,'price'=>700000,'old_price'=>900000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2020/10/lang-hoa-hong-dep-tang-20-10-e1602534065645.jpg','status'=>1],
            ['id'=>29,'name'=>'Hộp Hoa Hồng Sáp Mới Nhập','product_alias'=>'hop-hoa-hong-sap-moi-nhap','cat_id'=>4,'price'=>1000000,'old_price'=>1200000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/01/bo-hoa-14-2-300x300.jpg','status'=>1],
            ['id'=>30,'name'=>'Bó Hoa Mẫu Đơn Sáp Cực Đẹp','product_alias'=>'bo-hoa-mau-don-sap-cuc-dep','cat_id'=>4,'price'=>800000,'old_price'=>1000000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/hoa-cuc-mau-don-hong-300x300.jpg','status'=>1],
            ['id'=>31,'name'=>'Bó Hoa Hướng Dương Sáp','product_alias'=>'bo-hoa-huong-duong-sap','cat_id'=>4,'price'=>900000,'old_price'=>1200000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/02/hoa-huong-duong-scaled-e1645776177570-300x300.jpeg','status'=>1],
            ['id'=>32,'name'=>'Bó Hoa Hồng Pastel Sáp','product_alias'=>'bo-hoa-hong-pastel-sap','cat_id'=>4,'price'=>800000,'old_price'=>1000000,'content'=>'Hộp hoa hồng sáp tone màu kem trắng nhã nhặn, xinh yêu. Chắc chắn đây sẽ là món quà sinh nhật tuyệt vời dành tặng người bạn yêu thương.','description'=>'Hoa tặng sinh nhật người yêu luôn sẵn nhiều mẫu đẹp tại Hanoi Florist.','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2021/08/bo-hoa-hong-pastel-dep-300x300.jpg','status'=>1],
            ['id'=>33,'name'=>'Lẵng Hoa Khai Trương Đẹp Hồng Đỏ','product_alias'=>'lang-hoa-khai-truong-dep-hong-do','cat_id'=>5,'price'=>1500000,'old_price'=>2000000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2020/09/mau-hoa-2-tang-khai-truong-768x1180.jpg','status'=>1],
            ['id'=>34,'name'=>'Lẵng Hoa Khai Trương Đẹp Nhất','product_alias'=>'lang-hoa-khai-truong-dep-nhat','cat_id'=>5,'price'=>1200000,'old_price'=>1500000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2020/09/hoa-kahi-truong-dep-nhat-e1600837928993.jpg','status'=>1],
            ['id'=>35,'name'=>'Lẵng Hoa Khai Trương Hồng Đẹp','product_alias'=>'lang-hoa-khai-truong-hong-dep','cat_id'=>5,'price'=>1500000,'old_price'=>2000000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2020/09/lang-hoa-2-tang-dep-scaled-e1600620115117.jpg','status'=>1],
            ['id'=>36,'name'=>'Mẫu Hoa Khai Trương Rẻ Đẹp','product_alias'=>'mau-hoa-khai-truong-re-dep','cat_id'=>5,'price'=>1000000,'old_price'=>1200000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2020/09/mau-hoa-khai-truong-re-1.jpg','status'=>1],
            ['id'=>37,'name'=>'Hoa Tặng Khai Trương Cửa Hàng','product_alias'=>'hoa-tang-khai-truong-cua-hang','cat_id'=>5,'price'=>1200000,'old_price'=>1500000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/09/hoa-tang-khai-truong-cua-hang.jpg','status'=>1],
            ['id'=>38,'name'=>'Giỏ Hoa Chúc Mừng Khai Trương Đẹp','product_alias'=>'gio-hoa-chuc-mung-khai-truong-dep','cat_id'=>5,'price'=>2000000,'old_price'=>2500000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2022/10/gio-hoa-chuc-mung-dep.jpg','status'=>1],
            ['id'=>39,'name'=>'Lẵng Hoa Khai Trương Ấn Tượng Nhất','product_alias'=>'lang-hoa-khai-truong-an-tuong-nhat','cat_id'=>5,'price'=>1800000,'old_price'=>2000000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'http://hoahanoi.com.vn/wp-content/uploads/2020/10/lang-hoa-dep-chuc-mung-ngay-20-10-1-scaled-e1602530003458.jpg','status'=>1],
            ['id'=>40,'name'=>'Lẵng Hoa Chúc Mừng Khai Trương','product_alias'=>'lang-hoa-chuc-mung-khai-truong','cat_id'=>5,'price'=>1600000,'old_price'=>2000000,'content'=>'Nếu bạn cần một lẵng hoa khai trương với ngân sách vừa phải, thì mẫu hoa này là một lựa chọn vô cùng hợp lý!','description'=>'Lẵng hoa tone đỏ trắng là chủ đạo, kết hợp những bông hồng đỏ rực rỡ với lan tường trắng và hoa cẩm tú cầu xinh xắn !','image'=>'https://hoahanoi.com.vn/wp-content/uploads/2022/09/dat-lang-hoa-chuc-mung-khai-truong-1-300x300.jpg','status'=>1],
            
        ]);
    }
}
